########################################################################
##  This is a script that checks that the library is able to compile  ##
########################################################################

name: Ardiuno Driver Compile Check
on:
  push:
    branches:
      - master
  
  pull_request:
    branches:
      - master

jobs:
  compile_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create Library
        run: zip -r SW-420-Driver.zip src/ library.properties
