########################################################################
##  This is a script that checks that the library is able to compile  ##
########################################################################

name: Ardiuno Driver Compile Check
on:
  push:
    branches:
      - master
  
  pull_request:
    branches:
      - master

jobs:
  compile_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create Zip File for Library
        run: zip -r CustomSW-420-Driver.zip examples/ src/ library.properties

      - name: Checkout Library Compilance
        uses: arduino/arduino-lint-action@v1
        with:
          project-type: library

      - name: Compile Check
        uses: ArminJo/arduino-test-compile@v3
        with:
          arduino-board-fqbn: arduino:avr:uno

      - name: Create Directory for Download
        run: mkdir SW-420-Driver/

      - name: Copy files to Directory
        run: cp -r src/ SW-420-Driver/ && cp -r examples/ SW-420-Driver/ && cp library.properties SW-420-Driver/

      - name: Deploy 
        uses: actions/upload-artifact@v3
        with:
            name: SW-420-Driver
            path: SW-420-Driver/